
-- Seed all 200 game cards
-- SPEED ARCHETYPE - 20 Common
INSERT INTO public.game_cards (name, brand, model, archetype, rarity, speed, resilience, adaptability, power, hp) VALUES
('Toyota Corolla', 'Toyota', 'Corolla', 'speed', 'common', 5, 2, 2, 3, 10),
('Honda Civic', 'Honda', 'Civic', 'speed', 'common', 5, 3, 2, 2, 10),
('Mazda MX-5', 'Mazda', 'MX-5', 'speed', 'common', 6, 2, 2, 2, 10),
('Fiat Punto', 'Fiat', 'Punto', 'speed', 'common', 5, 2, 3, 2, 10),
('Peugeot 206', 'Peugeot', '206', 'speed', 'common', 5, 3, 2, 2, 10),
('Renault Clio', 'Renault', 'Clio', 'speed', 'common', 5, 2, 2, 3, 10),
('Suzuki Swift', 'Suzuki', 'Swift', 'speed', 'common', 6, 2, 2, 3, 10),
('VW Polo', 'VW', 'Polo', 'speed', 'common', 5, 3, 2, 2, 10),
('Opel Corsa', 'Opel', 'Corsa', 'speed', 'common', 5, 2, 3, 2, 10),
('Seat Ibiza', 'Seat', 'Ibiza', 'speed', 'common', 5, 2, 2, 3, 10),
('Hyundai i20', 'Hyundai', 'i20', 'speed', 'common', 5, 3, 2, 2, 10),
('Kia Rio', 'Kia', 'Rio', 'speed', 'common', 5, 2, 2, 3, 10),
('Dacia Sandero', 'Dacia', 'Sandero', 'speed', 'common', 4, 3, 3, 2, 10),
('Citroën C3', 'Citroën', 'C3', 'speed', 'common', 5, 2, 3, 2, 10),
('Ford Fiesta', 'Ford', 'Fiesta', 'speed', 'common', 5, 3, 2, 3, 10),
('Nissan Micra', 'Nissan', 'Micra', 'speed', 'common', 5, 2, 2, 3, 10),
('Skoda Fabia', 'Skoda', 'Fabia', 'speed', 'common', 5, 3, 2, 2, 10),
('Mini One', 'Mini', 'One', 'speed', 'common', 6, 2, 2, 2, 10),
('Smart ForTwo', 'Smart', 'ForTwo', 'speed', 'common', 5, 2, 3, 2, 10),
('Lancia Ypsilon', 'Lancia', 'Ypsilon', 'speed', 'common', 5, 2, 2, 3, 10),
-- SPEED - 15 Uncommon
('BMW M135i', 'BMW', 'M135i', 'speed', 'uncommon', 7, 4, 3, 4, 15),
('Audi S3', 'Audi', 'S3', 'speed', 'uncommon', 7, 4, 4, 3, 15),
('Mercedes A35 AMG', 'Mercedes', 'A35 AMG', 'speed', 'uncommon', 7, 4, 3, 4, 15),
('VW Golf GTI', 'VW', 'Golf GTI', 'speed', 'uncommon', 7, 4, 3, 4, 15),
('Honda Civic Type R', 'Honda', 'Civic Type R', 'speed', 'uncommon', 8, 3, 3, 4, 15),
('Toyota GR Yaris', 'Toyota', 'GR Yaris', 'speed', 'uncommon', 8, 3, 4, 3, 15),
('Ford Focus ST', 'Ford', 'Focus ST', 'speed', 'uncommon', 7, 4, 3, 4, 15),
('Hyundai i30 N', 'Hyundai', 'i30 N', 'speed', 'uncommon', 7, 4, 4, 3, 15),
('Renault Mégane RS', 'Renault', 'Mégane RS', 'speed', 'uncommon', 7, 3, 4, 4, 15),
('Peugeot 308 GTi', 'Peugeot', '308 GTi', 'speed', 'uncommon', 7, 4, 3, 4, 15),
('Alfa Romeo Giulietta QV', 'Alfa Romeo', 'Giulietta QV', 'speed', 'uncommon', 7, 3, 4, 4, 15),
('Mini JCW', 'Mini', 'JCW', 'speed', 'uncommon', 8, 3, 3, 4, 15),
('Seat Leon Cupra', 'Seat', 'Leon Cupra', 'speed', 'uncommon', 7, 4, 4, 3, 15),
('Mazda MX-5 RF', 'Mazda', 'MX-5 RF', 'speed', 'uncommon', 7, 3, 4, 4, 15),
('Subaru BRZ', 'Subaru', 'BRZ', 'speed', 'uncommon', 7, 3, 4, 4, 15),
-- SPEED - 10 Rare
('Porsche 718 Cayman', 'Porsche', '718 Cayman', 'speed', 'rare', 9, 5, 5, 6, 22),
('BMW M2', 'BMW', 'M2', 'speed', 'rare', 9, 5, 5, 6, 22),
('Audi RS3', 'Audi', 'RS3', 'speed', 'rare', 9, 5, 5, 6, 22),
('Mercedes C63 AMG', 'Mercedes', 'C63 AMG', 'speed', 'rare', 9, 6, 4, 6, 22),
('Lotus Elise', 'Lotus', 'Elise', 'speed', 'rare', 10, 4, 5, 5, 22),
('Alpine A110', 'Alpine', 'A110', 'speed', 'rare', 10, 4, 5, 5, 22),
('Toyota GR Supra', 'Toyota', 'GR Supra', 'speed', 'rare', 9, 5, 5, 6, 22),
('Nissan 370Z Nismo', 'Nissan', '370Z Nismo', 'speed', 'rare', 9, 5, 5, 6, 22),
('Chevrolet Corvette C7', 'Chevrolet', 'Corvette C7', 'speed', 'rare', 9, 5, 4, 7, 22),
('Jaguar F-Type R', 'Jaguar', 'F-Type R', 'speed', 'rare', 9, 5, 5, 6, 22),
-- SPEED - 5 Mythic
('Ferrari F8 Tributo', 'Ferrari', 'F8 Tributo', 'speed', 'mythic', 10, 7, 7, 8, 32),
('McLaren 720S', 'McLaren', '720S', 'speed', 'mythic', 10, 7, 7, 8, 32),
('Lamborghini Huracán EVO', 'Lamborghini', 'Huracán EVO', 'speed', 'mythic', 10, 7, 7, 9, 32),
('Porsche 911 GT3 RS', 'Porsche', '911 GT3 RS', 'speed', 'mythic', 10, 8, 7, 8, 32),
('Bugatti Chiron', 'Bugatti', 'Chiron', 'speed', 'mythic', 10, 8, 7, 9, 32),
-- RESILIENCE ARCHETYPE - 20 Common
('Toyota Land Cruiser 70', 'Toyota', 'Land Cruiser 70', 'resilience', 'common', 2, 5, 3, 2, 10),
('Jeep Wrangler', 'Jeep', 'Wrangler', 'resilience', 'common', 2, 6, 2, 2, 10),
('Land Rover Defender 90', 'Land Rover', 'Defender 90', 'resilience', 'common', 2, 5, 3, 2, 10),
('Suzuki Jimny', 'Suzuki', 'Jimny', 'resilience', 'common', 3, 5, 2, 2, 10),
('Mitsubishi Pajero', 'Mitsubishi', 'Pajero', 'resilience', 'common', 2, 5, 3, 2, 10),
('Nissan Patrol', 'Nissan', 'Patrol', 'resilience', 'common', 2, 6, 2, 2, 10),
('Ford Bronco Sport', 'Ford', 'Bronco Sport', 'resilience', 'common', 3, 5, 2, 2, 10),
('Chevrolet Tahoe', 'Chevrolet', 'Tahoe', 'resilience', 'common', 2, 5, 3, 2, 10),
('Dodge Durango', 'Dodge', 'Durango', 'resilience', 'common', 2, 5, 2, 3, 10),
('GMC Yukon', 'GMC', 'Yukon', 'resilience', 'common', 2, 5, 3, 2, 10),
('Toyota 4Runner', 'Toyota', '4Runner', 'resilience', 'common', 2, 6, 2, 2, 10),
('Isuzu Trooper', 'Isuzu', 'Trooper', 'resilience', 'common', 2, 5, 3, 2, 10),
('Ssangyong Rexton', 'Ssangyong', 'Rexton', 'resilience', 'common', 2, 5, 2, 3, 10),
('Dacia Duster', 'Dacia', 'Duster', 'resilience', 'common', 3, 5, 2, 2, 10),
('Lada Niva', 'Lada', 'Niva', 'resilience', 'common', 2, 5, 3, 2, 10),
('UAZ Hunter', 'UAZ', 'Hunter', 'resilience', 'common', 2, 6, 2, 2, 10),
('Mahindra Thar', 'Mahindra', 'Thar', 'resilience', 'common', 2, 5, 3, 2, 10),
('Great Wall Hover', 'Great Wall', 'Hover', 'resilience', 'common', 3, 5, 2, 2, 10),
('Tata Safari', 'Tata', 'Safari', 'resilience', 'common', 2, 5, 3, 2, 10),
('Fiat Panda 4x4', 'Fiat', 'Panda 4x4', 'resilience', 'common', 3, 5, 2, 2, 10),
-- RESILIENCE - 15 Uncommon
('Toyota Land Cruiser 200', 'Toyota', 'Land Cruiser 200', 'resilience', 'uncommon', 3, 7, 4, 4, 15),
('Jeep Grand Cherokee', 'Jeep', 'Grand Cherokee', 'resilience', 'uncommon', 4, 7, 3, 4, 15),
('Land Rover Discovery', 'Land Rover', 'Discovery', 'resilience', 'uncommon', 3, 7, 4, 4, 15),
('Mercedes G350d', 'Mercedes', 'G350d', 'resilience', 'uncommon', 3, 8, 3, 4, 15),
('Ford F-150', 'Ford', 'F-150', 'resilience', 'uncommon', 3, 7, 4, 4, 15),
('RAM 1500', 'RAM', '1500', 'resilience', 'uncommon', 3, 7, 3, 5, 15),
('Chevrolet Silverado', 'Chevrolet', 'Silverado', 'resilience', 'uncommon', 3, 7, 4, 4, 15),
('Toyota Hilux', 'Toyota', 'Hilux', 'resilience', 'uncommon', 4, 7, 4, 3, 15),
('Nissan Navara', 'Nissan', 'Navara', 'resilience', 'uncommon', 4, 7, 3, 4, 15),
('VW Amarok', 'VW', 'Amarok', 'resilience', 'uncommon', 4, 7, 4, 3, 15),
('Ford Ranger Raptor', 'Ford', 'Ranger Raptor', 'resilience', 'uncommon', 4, 7, 4, 4, 15),
('Mitsubishi L200', 'Mitsubishi', 'L200', 'resilience', 'uncommon', 3, 7, 4, 4, 15),
('Isuzu D-Max', 'Isuzu', 'D-Max', 'resilience', 'uncommon', 3, 7, 4, 4, 15),
('Hummer H3', 'Hummer', 'H3', 'resilience', 'uncommon', 3, 8, 3, 4, 15),
('Jeep Gladiator', 'Jeep', 'Gladiator', 'resilience', 'uncommon', 3, 7, 4, 4, 15),
-- RESILIENCE - 10 Rare
('Mercedes G63 AMG', 'Mercedes', 'G63 AMG', 'resilience', 'rare', 5, 9, 5, 6, 22),
('Land Rover Defender V8', 'Land Rover', 'Defender V8', 'resilience', 'rare', 5, 9, 5, 6, 22),
('Toyota Land Cruiser 300', 'Toyota', 'Land Cruiser 300', 'resilience', 'rare', 4, 9, 6, 6, 22),
('Jeep Wrangler Rubicon 392', 'Jeep', 'Wrangler Rubicon 392', 'resilience', 'rare', 5, 9, 5, 6, 22),
('Ford F-150 Raptor', 'Ford', 'F-150 Raptor', 'resilience', 'rare', 5, 9, 5, 6, 22),
('RAM TRX', 'RAM', 'TRX', 'resilience', 'rare', 5, 8, 5, 7, 22),
('Rivian R1T', 'Rivian', 'R1T', 'resilience', 'rare', 5, 9, 6, 5, 22),
('Lamborghini Urus', 'Lamborghini', 'Urus', 'resilience', 'rare', 6, 8, 5, 6, 22),
('Bentley Bentayga', 'Bentley', 'Bentayga', 'resilience', 'rare', 5, 9, 5, 6, 22),
('Rolls-Royce Cullinan', 'Rolls-Royce', 'Cullinan', 'resilience', 'rare', 4, 10, 5, 6, 22),
-- RESILIENCE - 5 Mythic
('Mercedes G63 AMG 6x6', 'Mercedes', 'G63 AMG 6x6', 'resilience', 'mythic', 6, 10, 7, 9, 32),
('Brabus G900', 'Brabus', 'G900', 'resilience', 'mythic', 7, 10, 7, 8, 32),
('Karlmann King', 'Karlmann', 'King', 'resilience', 'mythic', 5, 10, 8, 9, 32),
('Marauder Armoured', 'Marauder', 'Armoured', 'resilience', 'mythic', 4, 10, 8, 10, 32),
('Rezvani Tank Military', 'Rezvani', 'Tank Military', 'resilience', 'mythic', 6, 10, 8, 8, 32),
-- ADAPTABILITY ARCHETYPE - 20 Common
('Toyota Prius', 'Toyota', 'Prius', 'adaptability', 'common', 3, 2, 5, 2, 10),
('Honda Jazz', 'Honda', 'Jazz', 'adaptability', 'common', 3, 2, 5, 2, 10),
('Renault Captur', 'Renault', 'Captur', 'adaptability', 'common', 2, 3, 5, 2, 10),
('Peugeot 3008', 'Peugeot', '3008', 'adaptability', 'common', 2, 3, 5, 2, 10),
('Citroën C4 Cactus', 'Citroën', 'C4 Cactus', 'adaptability', 'common', 2, 2, 6, 2, 10),
('Nissan Juke', 'Nissan', 'Juke', 'adaptability', 'common', 3, 2, 5, 2, 10),
('Kia Niro', 'Kia', 'Niro', 'adaptability', 'common', 3, 2, 5, 2, 10),
('Hyundai Kona', 'Hyundai', 'Kona', 'adaptability', 'common', 3, 2, 5, 2, 10),
('Skoda Karoq', 'Skoda', 'Karoq', 'adaptability', 'common', 2, 3, 5, 2, 10),
('VW T-Cross', 'VW', 'T-Cross', 'adaptability', 'common', 2, 3, 5, 2, 10),
('Opel Crossland', 'Opel', 'Crossland', 'adaptability', 'common', 2, 3, 5, 2, 10),
('Ford Puma', 'Ford', 'Puma', 'adaptability', 'common', 3, 2, 5, 2, 10),
('Mazda CX-3', 'Mazda', 'CX-3', 'adaptability', 'common', 3, 2, 5, 2, 10),
('Subaru XV', 'Subaru', 'XV', 'adaptability', 'common', 2, 3, 5, 2, 10),
('Mitsubishi Eclipse Cross', 'Mitsubishi', 'Eclipse Cross', 'adaptability', 'common', 2, 2, 6, 2, 10),
('Suzuki Vitara', 'Suzuki', 'Vitara', 'adaptability', 'common', 2, 3, 5, 2, 10),
('Seat Arona', 'Seat', 'Arona', 'adaptability', 'common', 3, 2, 5, 2, 10),
('Fiat 500X', 'Fiat', '500X', 'adaptability', 'common', 2, 2, 6, 2, 10),
('Jeep Renegade', 'Jeep', 'Renegade', 'adaptability', 'common', 2, 3, 5, 2, 10),
('MG ZS', 'MG', 'ZS', 'adaptability', 'common', 3, 2, 5, 2, 10),
-- ADAPTABILITY - 15 Uncommon
('Tesla Model 3', 'Tesla', 'Model 3', 'adaptability', 'uncommon', 4, 3, 7, 4, 15),
('BMW i4', 'BMW', 'i4', 'adaptability', 'uncommon', 4, 4, 7, 3, 15),
('Audi Q5', 'Audi', 'Q5', 'adaptability', 'uncommon', 3, 4, 7, 4, 15),
('Mercedes GLC', 'Mercedes', 'GLC', 'adaptability', 'uncommon', 3, 4, 7, 4, 15),
('Volvo XC60', 'Volvo', 'XC60', 'adaptability', 'uncommon', 3, 5, 7, 3, 15),
('Porsche Macan', 'Porsche', 'Macan', 'adaptability', 'uncommon', 5, 4, 6, 4, 15),
('Jaguar E-Pace', 'Jaguar', 'E-Pace', 'adaptability', 'uncommon', 4, 4, 7, 3, 15),
('Alfa Romeo Stelvio', 'Alfa Romeo', 'Stelvio', 'adaptability', 'uncommon', 4, 3, 7, 4, 15),
('Lexus NX', 'Lexus', 'NX', 'adaptability', 'uncommon', 3, 4, 7, 4, 15),
('Infiniti QX50', 'Infiniti', 'QX50', 'adaptability', 'uncommon', 3, 4, 7, 4, 15),
('Genesis GV70', 'Genesis', 'GV70', 'adaptability', 'uncommon', 4, 4, 7, 3, 15),
('DS 7 Crossback', 'DS', '7 Crossback', 'adaptability', 'uncommon', 3, 4, 7, 4, 15),
('Maserati Grecale', 'Maserati', 'Grecale', 'adaptability', 'uncommon', 5, 3, 7, 4, 15),
('Cupra Formentor', 'Cupra', 'Formentor', 'adaptability', 'uncommon', 5, 3, 7, 4, 15),
('Polestar 2', 'Polestar', '2', 'adaptability', 'uncommon', 4, 4, 7, 3, 15),
-- ADAPTABILITY - 10 Rare
('Tesla Model S Plaid', 'Tesla', 'Model S Plaid', 'adaptability', 'rare', 6, 5, 8, 6, 22),
('Porsche Cayenne Turbo', 'Porsche', 'Cayenne Turbo', 'adaptability', 'rare', 6, 5, 8, 6, 22),
('BMW X5 M', 'BMW', 'X5 M', 'adaptability', 'rare', 6, 6, 7, 6, 22),
('Audi RS Q8', 'Audi', 'RS Q8', 'adaptability', 'rare', 6, 6, 7, 6, 22),
('Mercedes GLE 63', 'Mercedes', 'GLE 63', 'adaptability', 'rare', 5, 6, 8, 6, 22),
('Range Rover Sport SVR', 'Range Rover', 'Sport SVR', 'adaptability', 'rare', 6, 6, 7, 6, 22),
('Maserati Levante Trofeo', 'Maserati', 'Levante Trofeo', 'adaptability', 'rare', 6, 5, 8, 6, 22),
('Aston Martin DBX', 'Aston Martin', 'DBX', 'adaptability', 'rare', 5, 6, 8, 6, 22),
('Ferrari Purosangue', 'Ferrari', 'Purosangue', 'adaptability', 'rare', 7, 5, 8, 5, 22),
('Lotus Eletre', 'Lotus', 'Eletre', 'adaptability', 'rare', 6, 5, 8, 6, 22),
-- ADAPTABILITY - 5 Mythic
('Rimac Nevera', 'Rimac', 'Nevera', 'adaptability', 'mythic', 9, 7, 9, 7, 32),
('Tesla Roadster 2025', 'Tesla', 'Roadster 2025', 'adaptability', 'mythic', 9, 7, 9, 7, 32),
('Koenigsegg Gemera', 'Koenigsegg', 'Gemera', 'adaptability', 'mythic', 8, 7, 10, 7, 32),
('Aston Martin Valkyrie', 'Aston Martin', 'Valkyrie', 'adaptability', 'mythic', 9, 7, 9, 8, 32),
('Pagani Utopia', 'Pagani', 'Utopia', 'adaptability', 'mythic', 8, 7, 10, 8, 32),
-- POWER ARCHETYPE - 20 Common
('Ford Mustang V6', 'Ford', 'Mustang V6', 'power', 'common', 2, 3, 2, 5, 10),
('Chevrolet Camaro LT', 'Chevrolet', 'Camaro LT', 'power', 'common', 3, 2, 2, 5, 10),
('Dodge Challenger SXT', 'Dodge', 'Challenger SXT', 'power', 'common', 2, 3, 2, 5, 10),
('Pontiac Firebird', 'Pontiac', 'Firebird', 'power', 'common', 2, 2, 3, 5, 10),
('Mercury Cougar', 'Mercury', 'Cougar', 'power', 'common', 2, 3, 2, 5, 10),
('Chrysler 300', 'Chrysler', '300', 'power', 'common', 2, 3, 2, 5, 10),
('Buick Grand National', 'Buick', 'Grand National', 'power', 'common', 3, 2, 2, 5, 10),
('Oldsmobile 442', 'Oldsmobile', '442', 'power', 'common', 2, 2, 3, 5, 10),
('Plymouth Barracuda', 'Plymouth', 'Barracuda', 'power', 'common', 2, 3, 2, 5, 10),
('AMC Javelin', 'AMC', 'Javelin', 'power', 'common', 2, 2, 3, 5, 10),
('Holden Commodore', 'Holden', 'Commodore', 'power', 'common', 3, 2, 2, 5, 10),
('Vauxhall VXR8', 'Vauxhall', 'VXR8', 'power', 'common', 3, 2, 2, 5, 10),
('HSV GTS', 'HSV', 'GTS', 'power', 'common', 3, 2, 2, 5, 10),
('Ford Falcon XR6', 'Ford', 'Falcon XR6', 'power', 'common', 2, 2, 3, 5, 10),
('Nissan Silvia S13', 'Nissan', 'Silvia S13', 'power', 'common', 3, 2, 2, 5, 10),
('Mitsubishi Eclipse', 'Mitsubishi', 'Eclipse', 'power', 'common', 3, 2, 2, 5, 10),
('Toyota Celica', 'Toyota', 'Celica', 'power', 'common', 3, 2, 2, 5, 10),
('Mazda RX-7 FC', 'Mazda', 'RX-7 FC', 'power', 'common', 3, 2, 2, 5, 10),
('Honda Prelude', 'Honda', 'Prelude', 'power', 'common', 3, 2, 2, 5, 10),
('Subaru Legacy GT', 'Subaru', 'Legacy GT', 'power', 'common', 2, 3, 2, 5, 10),
-- POWER - 15 Uncommon
('Ford Mustang GT', 'Ford', 'Mustang GT', 'power', 'uncommon', 4, 3, 3, 8, 15),
('Chevrolet Camaro SS', 'Chevrolet', 'Camaro SS', 'power', 'uncommon', 4, 3, 3, 8, 15),
('Dodge Challenger R/T', 'Dodge', 'Challenger R/T', 'power', 'uncommon', 3, 4, 3, 8, 15),
('Nissan GT-R', 'Nissan', 'GT-R', 'power', 'uncommon', 5, 3, 3, 7, 15),
('Subaru WRX STI', 'Subaru', 'WRX STI', 'power', 'uncommon', 4, 4, 3, 7, 15),
('Mitsubishi Lancer Evo X', 'Mitsubishi', 'Lancer Evo X', 'power', 'uncommon', 4, 3, 4, 7, 15),
('BMW M3 E46', 'BMW', 'M3 E46', 'power', 'uncommon', 4, 4, 3, 7, 15),
('Audi RS4 B7', 'Audi', 'RS4 B7', 'power', 'uncommon', 4, 4, 3, 7, 15),
('Mercedes C63 W204', 'Mercedes', 'C63 W204', 'power', 'uncommon', 4, 4, 3, 7, 15),
('Lexus IS F', 'Lexus', 'IS F', 'power', 'uncommon', 4, 4, 3, 7, 15),
('Cadillac CTS-V', 'Cadillac', 'CTS-V', 'power', 'uncommon', 4, 3, 3, 8, 15),
('Pontiac GTO', 'Pontiac', 'GTO', 'power', 'uncommon', 3, 4, 3, 8, 15),
('Shelby GT350', 'Shelby', 'GT350', 'power', 'uncommon', 4, 3, 4, 7, 15),
('Mazda RX-7 FD', 'Mazda', 'RX-7 FD', 'power', 'uncommon', 5, 3, 3, 7, 15),
('Toyota Supra MK4', 'Toyota', 'Supra MK4', 'power', 'uncommon', 5, 3, 3, 7, 15),
-- POWER - 10 Rare
('Dodge Challenger Hellcat', 'Dodge', 'Challenger Hellcat', 'power', 'rare', 5, 5, 4, 9, 22),
('Ford Mustang Shelby GT500', 'Ford', 'Mustang Shelby GT500', 'power', 'rare', 6, 4, 4, 9, 22),
('Chevrolet Corvette Z06', 'Chevrolet', 'Corvette Z06', 'power', 'rare', 6, 5, 4, 9, 22),
('Nissan GT-R Nismo', 'Nissan', 'GT-R Nismo', 'power', 'rare', 6, 5, 5, 8, 22),
('BMW M5 CS', 'BMW', 'M5 CS', 'power', 'rare', 6, 5, 5, 8, 22),
('Audi RS6 Avant', 'Audi', 'RS6 Avant', 'power', 'rare', 5, 5, 5, 9, 22),
('Mercedes E63 S', 'Mercedes', 'E63 S', 'power', 'rare', 6, 5, 4, 9, 22),
('Dodge Viper ACR', 'Dodge', 'Viper ACR', 'power', 'rare', 6, 4, 4, 10, 22),
('Chevrolet Camaro ZL1', 'Chevrolet', 'Camaro ZL1', 'power', 'rare', 6, 5, 4, 9, 22),
('Shelby Super Snake', 'Shelby', 'Super Snake', 'power', 'rare', 5, 5, 4, 10, 22),
-- POWER - 5 Mythic
('Koenigsegg Jesko', 'Koenigsegg', 'Jesko', 'power', 'mythic', 9, 7, 7, 10, 32),
('Hennessey Venom F5', 'Hennessey', 'Venom F5', 'power', 'mythic', 9, 7, 7, 10, 32),
('SSC Tuatara', 'SSC', 'Tuatara', 'power', 'mythic', 9, 7, 7, 10, 32),
('Lamborghini Aventador SVJ', 'Lamborghini', 'Aventador SVJ', 'power', 'mythic', 9, 8, 7, 10, 32),
('Ferrari LaFerrari', 'Ferrari', 'LaFerrari', 'power', 'mythic', 9, 8, 7, 10, 32);

-- Add RLS policy for friends to view each other's game cards
CREATE POLICY "Friends can view friend game cards"
ON public.user_game_cards FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.friendships f
    WHERE f.status = 'accepted'
    AND ((f.requester_id = auth.uid() AND f.addressee_id = user_game_cards.user_id)
      OR (f.addressee_id = auth.uid() AND f.requester_id = user_game_cards.user_id))
  )
);
